name: libri_ai
description: "A semantic book recommender engine powered by Flutter, Supabase Vector Search, and Google Gemini."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # Core
  flutter_dotenv: ^6.0.0
  go_router: ^14.2.0          # v14 is the stable standard for Dart 3.5
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  gap: ^3.0.1
  
  # Riverpod (Stable 2.x Ecosystem)
  flutter_riverpod: ^2.5.1    # Do not use 3.x yet
  riverpod_annotation: ^2.3.5 
  
  # Data
  supabase: ^2.0.0
  supabase_flutter: ^2.6.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Code Gen (Annotations)
  freezed_annotation: ^2.4.4  # Matches Freezed 2.x
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  dio: ^5.9.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Build Tools
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  
  # Generators (Must match the main dependencies)
  riverpod_generator: ^2.4.0  # Matches riverpod 2.x
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2             # Matches freezed_annotation 2.x
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_test: ^0.1.6
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  app_links: 6.3.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#121212"
    theme_color: "#121212"